apiVersion: v1
kind: Service
metadata:
  name: record-store-day
  labels:
    app: record-store-day
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: record-store-day
